package com.sofency.ssm.mapper;

import com.sofency.ssm.pojo.Candidate;
import com.sofency.ssm.pojo.CandidateExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface CandidateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table candidate
     *
     * @mbg.generated Mon Mar 30 22:02:34 CST 2020
     */
    long countByExample(CandidateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table candidate
     *
     * @mbg.generated Mon Mar 30 22:02:34 CST 2020
     */
    int deleteByExample(CandidateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table candidate
     *
     * @mbg.generated Mon Mar 30 22:02:34 CST 2020
     */
    int deleteByPrimaryKey(Integer candidateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table candidate
     *
     * @mbg.generated Mon Mar 30 22:02:34 CST 2020
     */
    int insert(Candidate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table candidate
     *
     * @mbg.generated Mon Mar 30 22:02:34 CST 2020
     */
    int insertSelective(Candidate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table candidate
     *
     * @mbg.generated Mon Mar 30 22:02:34 CST 2020
     */
    List<Candidate> selectByExampleWithRowbounds(CandidateExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table candidate
     *
     * @mbg.generated Mon Mar 30 22:02:34 CST 2020
     */
    List<Candidate> selectByExample(CandidateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table candidate
     *
     * @mbg.generated Mon Mar 30 22:02:34 CST 2020
     */
    Candidate selectByPrimaryKey(Integer candidateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table candidate
     *
     * @mbg.generated Mon Mar 30 22:02:34 CST 2020
     */
    int updateByExampleSelective(@Param("record") Candidate record, @Param("example") CandidateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table candidate
     *
     * @mbg.generated Mon Mar 30 22:02:34 CST 2020
     */
    int updateByExample(@Param("record") Candidate record, @Param("example") CandidateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table candidate
     *
     * @mbg.generated Mon Mar 30 22:02:34 CST 2020
     */
    int updateByPrimaryKeySelective(Candidate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table candidate
     *
     * @mbg.generated Mon Mar 30 22:02:34 CST 2020
     */
    int updateByPrimaryKey(Candidate record);
}