package com.sofency.ssm.mapper;

import com.sofency.ssm.pojo.Engineer;
import com.sofency.ssm.pojo.EngineerExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;
@Mapper
public interface EngineerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table engineer
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    long countByExample(EngineerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table engineer
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    int deleteByExample(EngineerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table engineer
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    int deleteByPrimaryKey(Integer engineerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table engineer
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    int insert(Engineer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table engineer
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    int insertSelective(Engineer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table engineer
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    List<Engineer> selectByExampleWithRowbounds(EngineerExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table engineer
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    List<Engineer> selectByExample(EngineerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table engineer
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    Engineer selectByPrimaryKey(Integer engineerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table engineer
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    int updateByExampleSelective(@Param("record") Engineer record, @Param("example") EngineerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table engineer
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    int updateByExample(@Param("record") Engineer record, @Param("example") EngineerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table engineer
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    int updateByPrimaryKeySelective(Engineer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table engineer
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    int updateByPrimaryKey(Engineer record);
}