package com.sofency.ssm.mapper;

import com.sofency.ssm.pojo.Fame;
import com.sofency.ssm.pojo.FameExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface FameMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fame
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    long countByExample(FameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fame
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    int deleteByExample(FameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fame
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    int deleteByPrimaryKey(Integer fameId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fame
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    int insert(Fame record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fame
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    int insertSelective(Fame record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fame
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    List<Fame> selectByExampleWithRowbounds(FameExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fame
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    List<Fame> selectByExample(FameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fame
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    Fame selectByPrimaryKey(Integer fameId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fame
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    int updateByExampleSelective(@Param("record") Fame record, @Param("example") FameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fame
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    int updateByExample(@Param("record") Fame record, @Param("example") FameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fame
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    int updateByPrimaryKeySelective(Fame record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fame
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    int updateByPrimaryKey(Fame record);
}