package com.sofency.ssm.mapper;

import com.sofency.ssm.pojo.GetFame;
import com.sofency.ssm.pojo.GetFameExample;
import com.sofency.ssm.pojo.GetFameKey;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import java.util.List;

public interface GetFameMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table getfame
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    long countByExample(GetFameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table getfame
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    int deleteByExample(GetFameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table getfame
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    int deleteByPrimaryKey(GetFameKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table getfame
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    int insert(GetFame record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table getfame
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    int insertSelective(GetFame record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table getfame
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    List<GetFame> selectByExampleWithRowbounds(GetFameExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table getfame
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    List<GetFame> selectByExample(GetFameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table getfame
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    GetFame selectByPrimaryKey(GetFameKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table getfame
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    int updateByExampleSelective(@Param("record") GetFame record, @Param("example") GetFameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table getfame
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    int updateByExample(@Param("record") GetFame record, @Param("example") GetFameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table getfame
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    int updateByPrimaryKeySelective(GetFame record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table getfame
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    int updateByPrimaryKey(GetFame record);
}