package com.sofency.ssm.mapper;

import com.sofency.ssm.pojo.Major;
import com.sofency.ssm.pojo.MajorExample;
import com.sofency.ssm.pojo.MajorKey;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface MajorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    long countByExample(MajorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    int deleteByExample(MajorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    int deleteByPrimaryKey(MajorKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    int insert(Major record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    int insertSelective(Major record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    List<Major> selectByExampleWithRowbounds(MajorExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    List<Major> selectByExample(MajorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    Major selectByPrimaryKey(MajorKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    int updateByExampleSelective(@Param("record") Major record, @Param("example") MajorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    int updateByExample(@Param("record") Major record, @Param("example") MajorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    int updateByPrimaryKeySelective(Major record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    int updateByPrimaryKey(Major record);
}