package com.sofency.ssm.pojo;

import java.io.Serializable;

public class Candidate implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column candidate.candidate_id
     *
     * @mbg.generated Mon Mar 30 22:02:34 CST 2020
     */
    private Integer candidateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column candidate.inst_id
     *
     * @mbg.generated Mon Mar 30 22:02:34 CST 2020
     */
    private Integer instId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column candidate.major_id
     *
     * @mbg.generated Mon Mar 30 22:02:34 CST 2020
     */
    private Integer majorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column candidate.candidate_name
     *
     * @mbg.generated Mon Mar 30 22:02:34 CST 2020
     */
    private String candidateName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column candidate.candidate_sex
     *
     * @mbg.generated Mon Mar 30 22:02:34 CST 2020
     */
    private String candidateSex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column candidate.candidate_tel
     *
     * @mbg.generated Mon Mar 30 22:02:34 CST 2020
     */
    private String candidateTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column candidate.candidate_email
     *
     * @mbg.generated Mon Mar 30 22:02:34 CST 2020
     */
    private String candidateEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column candidate.candidate_introduce
     *
     * @mbg.generated Mon Mar 30 22:02:34 CST 2020
     */
    private String candidateIntroduce;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column candidate.candidate_fame
     *
     * @mbg.generated Mon Mar 30 22:02:34 CST 2020
     */
    private String candidateFame;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column candidate.candidate_status
     *
     * @mbg.generated Mon Mar 30 22:02:34 CST 2020
     */
    private Byte candidateStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column candidate.candidate_id
     *
     * @return the value of candidate.candidate_id
     *
     * @mbg.generated Mon Mar 30 22:02:34 CST 2020
     */
    public Integer getCandidateId() {
        return candidateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column candidate.candidate_id
     *
     * @param candidateId the value for candidate.candidate_id
     *
     * @mbg.generated Mon Mar 30 22:02:34 CST 2020
     */
    public void setCandidateId(Integer candidateId) {
        this.candidateId = candidateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column candidate.inst_id
     *
     * @return the value of candidate.inst_id
     *
     * @mbg.generated Mon Mar 30 22:02:34 CST 2020
     */
    public Integer getInstId() {
        return instId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column candidate.inst_id
     *
     * @param instId the value for candidate.inst_id
     *
     * @mbg.generated Mon Mar 30 22:02:34 CST 2020
     */
    public void setInstId(Integer instId) {
        this.instId = instId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column candidate.major_id
     *
     * @return the value of candidate.major_id
     *
     * @mbg.generated Mon Mar 30 22:02:34 CST 2020
     */
    public Integer getMajorId() {
        return majorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column candidate.major_id
     *
     * @param majorId the value for candidate.major_id
     *
     * @mbg.generated Mon Mar 30 22:02:34 CST 2020
     */
    public void setMajorId(Integer majorId) {
        this.majorId = majorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column candidate.candidate_name
     *
     * @return the value of candidate.candidate_name
     *
     * @mbg.generated Mon Mar 30 22:02:34 CST 2020
     */
    public String getCandidateName() {
        return candidateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column candidate.candidate_name
     *
     * @param candidateName the value for candidate.candidate_name
     *
     * @mbg.generated Mon Mar 30 22:02:34 CST 2020
     */
    public void setCandidateName(String candidateName) {
        this.candidateName = candidateName == null ? null : candidateName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column candidate.candidate_sex
     *
     * @return the value of candidate.candidate_sex
     *
     * @mbg.generated Mon Mar 30 22:02:34 CST 2020
     */
    public String getCandidateSex() {
        return candidateSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column candidate.candidate_sex
     *
     * @param candidateSex the value for candidate.candidate_sex
     *
     * @mbg.generated Mon Mar 30 22:02:34 CST 2020
     */
    public void setCandidateSex(String candidateSex) {
        this.candidateSex = candidateSex == null ? null : candidateSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column candidate.candidate_tel
     *
     * @return the value of candidate.candidate_tel
     *
     * @mbg.generated Mon Mar 30 22:02:34 CST 2020
     */
    public String getCandidateTel() {
        return candidateTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column candidate.candidate_tel
     *
     * @param candidateTel the value for candidate.candidate_tel
     *
     * @mbg.generated Mon Mar 30 22:02:34 CST 2020
     */
    public void setCandidateTel(String candidateTel) {
        this.candidateTel = candidateTel == null ? null : candidateTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column candidate.candidate_email
     *
     * @return the value of candidate.candidate_email
     *
     * @mbg.generated Mon Mar 30 22:02:34 CST 2020
     */
    public String getCandidateEmail() {
        return candidateEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column candidate.candidate_email
     *
     * @param candidateEmail the value for candidate.candidate_email
     *
     * @mbg.generated Mon Mar 30 22:02:34 CST 2020
     */
    public void setCandidateEmail(String candidateEmail) {
        this.candidateEmail = candidateEmail == null ? null : candidateEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column candidate.candidate_introduce
     *
     * @return the value of candidate.candidate_introduce
     *
     * @mbg.generated Mon Mar 30 22:02:34 CST 2020
     */
    public String getCandidateIntroduce() {
        return candidateIntroduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column candidate.candidate_introduce
     *
     * @param candidateIntroduce the value for candidate.candidate_introduce
     *
     * @mbg.generated Mon Mar 30 22:02:34 CST 2020
     */
    public void setCandidateIntroduce(String candidateIntroduce) {
        this.candidateIntroduce = candidateIntroduce == null ? null : candidateIntroduce.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column candidate.candidate_fame
     *
     * @return the value of candidate.candidate_fame
     *
     * @mbg.generated Mon Mar 30 22:02:34 CST 2020
     */
    public String getCandidateFame() {
        return candidateFame;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column candidate.candidate_fame
     *
     * @param candidateFame the value for candidate.candidate_fame
     *
     * @mbg.generated Mon Mar 30 22:02:34 CST 2020
     */
    public void setCandidateFame(String candidateFame) {
        this.candidateFame = candidateFame == null ? null : candidateFame.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column candidate.candidate_status
     *
     * @return the value of candidate.candidate_status
     *
     * @mbg.generated Mon Mar 30 22:02:34 CST 2020
     */
    public Byte getCandidateStatus() {
        return candidateStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column candidate.candidate_status
     *
     * @param candidateStatus the value for candidate.candidate_status
     *
     * @mbg.generated Mon Mar 30 22:02:34 CST 2020
     */
    public void setCandidateStatus(Byte candidateStatus) {
        this.candidateStatus = candidateStatus;
    }
}