package com.sofency.ssm.pojo;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

public class EngineerExample  implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table engineer
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table engineer
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table engineer
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table engineer
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    public EngineerExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table engineer
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table engineer
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table engineer
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table engineer
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table engineer
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table engineer
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table engineer
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table engineer
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table engineer
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table engineer
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table engineer
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andEngineerIdIsNull() {
            addCriterion("engineer_id is null");
            return (Criteria) this;
        }

        public Criteria andEngineerIdIsNotNull() {
            addCriterion("engineer_id is not null");
            return (Criteria) this;
        }

        public Criteria andEngineerIdEqualTo(Integer value) {
            addCriterion("engineer_id =", value, "engineerId");
            return (Criteria) this;
        }

        public Criteria andEngineerIdNotEqualTo(Integer value) {
            addCriterion("engineer_id <>", value, "engineerId");
            return (Criteria) this;
        }

        public Criteria andEngineerIdGreaterThan(Integer value) {
            addCriterion("engineer_id >", value, "engineerId");
            return (Criteria) this;
        }

        public Criteria andEngineerIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("engineer_id >=", value, "engineerId");
            return (Criteria) this;
        }

        public Criteria andEngineerIdLessThan(Integer value) {
            addCriterion("engineer_id <", value, "engineerId");
            return (Criteria) this;
        }

        public Criteria andEngineerIdLessThanOrEqualTo(Integer value) {
            addCriterion("engineer_id <=", value, "engineerId");
            return (Criteria) this;
        }

        public Criteria andEngineerIdIn(List<Integer> values) {
            addCriterion("engineer_id in", values, "engineerId");
            return (Criteria) this;
        }

        public Criteria andEngineerIdNotIn(List<Integer> values) {
            addCriterion("engineer_id not in", values, "engineerId");
            return (Criteria) this;
        }

        public Criteria andEngineerIdBetween(Integer value1, Integer value2) {
            addCriterion("engineer_id between", value1, value2, "engineerId");
            return (Criteria) this;
        }

        public Criteria andEngineerIdNotBetween(Integer value1, Integer value2) {
            addCriterion("engineer_id not between", value1, value2, "engineerId");
            return (Criteria) this;
        }

        public Criteria andInstIdIsNull() {
            addCriterion("inst_id is null");
            return (Criteria) this;
        }

        public Criteria andInstIdIsNotNull() {
            addCriterion("inst_id is not null");
            return (Criteria) this;
        }

        public Criteria andInstIdEqualTo(Integer value) {
            addCriterion("inst_id =", value, "instId");
            return (Criteria) this;
        }

        public Criteria andInstIdNotEqualTo(Integer value) {
            addCriterion("inst_id <>", value, "instId");
            return (Criteria) this;
        }

        public Criteria andInstIdGreaterThan(Integer value) {
            addCriterion("inst_id >", value, "instId");
            return (Criteria) this;
        }

        public Criteria andInstIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("inst_id >=", value, "instId");
            return (Criteria) this;
        }

        public Criteria andInstIdLessThan(Integer value) {
            addCriterion("inst_id <", value, "instId");
            return (Criteria) this;
        }

        public Criteria andInstIdLessThanOrEqualTo(Integer value) {
            addCriterion("inst_id <=", value, "instId");
            return (Criteria) this;
        }

        public Criteria andInstIdIn(List<Integer> values) {
            addCriterion("inst_id in", values, "instId");
            return (Criteria) this;
        }

        public Criteria andInstIdNotIn(List<Integer> values) {
            addCriterion("inst_id not in", values, "instId");
            return (Criteria) this;
        }

        public Criteria andInstIdBetween(Integer value1, Integer value2) {
            addCriterion("inst_id between", value1, value2, "instId");
            return (Criteria) this;
        }

        public Criteria andInstIdNotBetween(Integer value1, Integer value2) {
            addCriterion("inst_id not between", value1, value2, "instId");
            return (Criteria) this;
        }

        public Criteria andMajorIdIsNull() {
            addCriterion("major_id is null");
            return (Criteria) this;
        }

        public Criteria andMajorIdIsNotNull() {
            addCriterion("major_id is not null");
            return (Criteria) this;
        }

        public Criteria andMajorIdEqualTo(Integer value) {
            addCriterion("major_id =", value, "majorId");
            return (Criteria) this;
        }

        public Criteria andMajorIdNotEqualTo(Integer value) {
            addCriterion("major_id <>", value, "majorId");
            return (Criteria) this;
        }

        public Criteria andMajorIdGreaterThan(Integer value) {
            addCriterion("major_id >", value, "majorId");
            return (Criteria) this;
        }

        public Criteria andMajorIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("major_id >=", value, "majorId");
            return (Criteria) this;
        }

        public Criteria andMajorIdLessThan(Integer value) {
            addCriterion("major_id <", value, "majorId");
            return (Criteria) this;
        }

        public Criteria andMajorIdLessThanOrEqualTo(Integer value) {
            addCriterion("major_id <=", value, "majorId");
            return (Criteria) this;
        }

        public Criteria andMajorIdIn(List<Integer> values) {
            addCriterion("major_id in", values, "majorId");
            return (Criteria) this;
        }

        public Criteria andMajorIdNotIn(List<Integer> values) {
            addCriterion("major_id not in", values, "majorId");
            return (Criteria) this;
        }

        public Criteria andMajorIdBetween(Integer value1, Integer value2) {
            addCriterion("major_id between", value1, value2, "majorId");
            return (Criteria) this;
        }

        public Criteria andMajorIdNotBetween(Integer value1, Integer value2) {
            addCriterion("major_id not between", value1, value2, "majorId");
            return (Criteria) this;
        }

        public Criteria andEngineerSexIsNull() {
            addCriterion("engineer_sex is null");
            return (Criteria) this;
        }

        public Criteria andEngineerSexIsNotNull() {
            addCriterion("engineer_sex is not null");
            return (Criteria) this;
        }

        public Criteria andEngineerSexEqualTo(String value) {
            addCriterion("engineer_sex =", value, "engineerSex");
            return (Criteria) this;
        }

        public Criteria andEngineerSexNotEqualTo(String value) {
            addCriterion("engineer_sex <>", value, "engineerSex");
            return (Criteria) this;
        }

        public Criteria andEngineerSexGreaterThan(String value) {
            addCriterion("engineer_sex >", value, "engineerSex");
            return (Criteria) this;
        }

        public Criteria andEngineerSexGreaterThanOrEqualTo(String value) {
            addCriterion("engineer_sex >=", value, "engineerSex");
            return (Criteria) this;
        }

        public Criteria andEngineerSexLessThan(String value) {
            addCriterion("engineer_sex <", value, "engineerSex");
            return (Criteria) this;
        }

        public Criteria andEngineerSexLessThanOrEqualTo(String value) {
            addCriterion("engineer_sex <=", value, "engineerSex");
            return (Criteria) this;
        }

        public Criteria andEngineerSexLike(String value) {
            addCriterion("engineer_sex like", value, "engineerSex");
            return (Criteria) this;
        }

        public Criteria andEngineerSexNotLike(String value) {
            addCriterion("engineer_sex not like", value, "engineerSex");
            return (Criteria) this;
        }

        public Criteria andEngineerSexIn(List<String> values) {
            addCriterion("engineer_sex in", values, "engineerSex");
            return (Criteria) this;
        }

        public Criteria andEngineerSexNotIn(List<String> values) {
            addCriterion("engineer_sex not in", values, "engineerSex");
            return (Criteria) this;
        }

        public Criteria andEngineerSexBetween(String value1, String value2) {
            addCriterion("engineer_sex between", value1, value2, "engineerSex");
            return (Criteria) this;
        }

        public Criteria andEngineerSexNotBetween(String value1, String value2) {
            addCriterion("engineer_sex not between", value1, value2, "engineerSex");
            return (Criteria) this;
        }

        public Criteria andEngineerNameIsNull() {
            addCriterion("engineer_name is null");
            return (Criteria) this;
        }

        public Criteria andEngineerNameIsNotNull() {
            addCriterion("engineer_name is not null");
            return (Criteria) this;
        }

        public Criteria andEngineerNameEqualTo(String value) {
            addCriterion("engineer_name =", value, "engineerName");
            return (Criteria) this;
        }

        public Criteria andEngineerNameNotEqualTo(String value) {
            addCriterion("engineer_name <>", value, "engineerName");
            return (Criteria) this;
        }

        public Criteria andEngineerNameGreaterThan(String value) {
            addCriterion("engineer_name >", value, "engineerName");
            return (Criteria) this;
        }

        public Criteria andEngineerNameGreaterThanOrEqualTo(String value) {
            addCriterion("engineer_name >=", value, "engineerName");
            return (Criteria) this;
        }

        public Criteria andEngineerNameLessThan(String value) {
            addCriterion("engineer_name <", value, "engineerName");
            return (Criteria) this;
        }

        public Criteria andEngineerNameLessThanOrEqualTo(String value) {
            addCriterion("engineer_name <=", value, "engineerName");
            return (Criteria) this;
        }

        public Criteria andEngineerNameLike(String value) {
            addCriterion("engineer_name like", value, "engineerName");
            return (Criteria) this;
        }

        public Criteria andEngineerNameNotLike(String value) {
            addCriterion("engineer_name not like", value, "engineerName");
            return (Criteria) this;
        }

        public Criteria andEngineerNameIn(List<String> values) {
            addCriterion("engineer_name in", values, "engineerName");
            return (Criteria) this;
        }

        public Criteria andEngineerNameNotIn(List<String> values) {
            addCriterion("engineer_name not in", values, "engineerName");
            return (Criteria) this;
        }

        public Criteria andEngineerNameBetween(String value1, String value2) {
            addCriterion("engineer_name between", value1, value2, "engineerName");
            return (Criteria) this;
        }

        public Criteria andEngineerNameNotBetween(String value1, String value2) {
            addCriterion("engineer_name not between", value1, value2, "engineerName");
            return (Criteria) this;
        }

        public Criteria andEngineerImgPathIsNull() {
            addCriterion("engineer_img_path is null");
            return (Criteria) this;
        }

        public Criteria andEngineerImgPathIsNotNull() {
            addCriterion("engineer_img_path is not null");
            return (Criteria) this;
        }

        public Criteria andEngineerImgPathEqualTo(String value) {
            addCriterion("engineer_img_path =", value, "engineerImgPath");
            return (Criteria) this;
        }

        public Criteria andEngineerImgPathNotEqualTo(String value) {
            addCriterion("engineer_img_path <>", value, "engineerImgPath");
            return (Criteria) this;
        }

        public Criteria andEngineerImgPathGreaterThan(String value) {
            addCriterion("engineer_img_path >", value, "engineerImgPath");
            return (Criteria) this;
        }

        public Criteria andEngineerImgPathGreaterThanOrEqualTo(String value) {
            addCriterion("engineer_img_path >=", value, "engineerImgPath");
            return (Criteria) this;
        }

        public Criteria andEngineerImgPathLessThan(String value) {
            addCriterion("engineer_img_path <", value, "engineerImgPath");
            return (Criteria) this;
        }

        public Criteria andEngineerImgPathLessThanOrEqualTo(String value) {
            addCriterion("engineer_img_path <=", value, "engineerImgPath");
            return (Criteria) this;
        }

        public Criteria andEngineerImgPathLike(String value) {
            addCriterion("engineer_img_path like", value, "engineerImgPath");
            return (Criteria) this;
        }

        public Criteria andEngineerImgPathNotLike(String value) {
            addCriterion("engineer_img_path not like", value, "engineerImgPath");
            return (Criteria) this;
        }

        public Criteria andEngineerImgPathIn(List<String> values) {
            addCriterion("engineer_img_path in", values, "engineerImgPath");
            return (Criteria) this;
        }

        public Criteria andEngineerImgPathNotIn(List<String> values) {
            addCriterion("engineer_img_path not in", values, "engineerImgPath");
            return (Criteria) this;
        }

        public Criteria andEngineerImgPathBetween(String value1, String value2) {
            addCriterion("engineer_img_path between", value1, value2, "engineerImgPath");
            return (Criteria) this;
        }

        public Criteria andEngineerImgPathNotBetween(String value1, String value2) {
            addCriterion("engineer_img_path not between", value1, value2, "engineerImgPath");
            return (Criteria) this;
        }

        public Criteria andEngineerTelIsNull() {
            addCriterion("engineer_tel is null");
            return (Criteria) this;
        }

        public Criteria andEngineerTelIsNotNull() {
            addCriterion("engineer_tel is not null");
            return (Criteria) this;
        }

        public Criteria andEngineerTelEqualTo(String value) {
            addCriterion("engineer_tel =", value, "engineerTel");
            return (Criteria) this;
        }

        public Criteria andEngineerTelNotEqualTo(String value) {
            addCriterion("engineer_tel <>", value, "engineerTel");
            return (Criteria) this;
        }

        public Criteria andEngineerTelGreaterThan(String value) {
            addCriterion("engineer_tel >", value, "engineerTel");
            return (Criteria) this;
        }

        public Criteria andEngineerTelGreaterThanOrEqualTo(String value) {
            addCriterion("engineer_tel >=", value, "engineerTel");
            return (Criteria) this;
        }

        public Criteria andEngineerTelLessThan(String value) {
            addCriterion("engineer_tel <", value, "engineerTel");
            return (Criteria) this;
        }

        public Criteria andEngineerTelLessThanOrEqualTo(String value) {
            addCriterion("engineer_tel <=", value, "engineerTel");
            return (Criteria) this;
        }

        public Criteria andEngineerTelLike(String value) {
            addCriterion("engineer_tel like", value, "engineerTel");
            return (Criteria) this;
        }

        public Criteria andEngineerTelNotLike(String value) {
            addCriterion("engineer_tel not like", value, "engineerTel");
            return (Criteria) this;
        }

        public Criteria andEngineerTelIn(List<String> values) {
            addCriterion("engineer_tel in", values, "engineerTel");
            return (Criteria) this;
        }

        public Criteria andEngineerTelNotIn(List<String> values) {
            addCriterion("engineer_tel not in", values, "engineerTel");
            return (Criteria) this;
        }

        public Criteria andEngineerTelBetween(String value1, String value2) {
            addCriterion("engineer_tel between", value1, value2, "engineerTel");
            return (Criteria) this;
        }

        public Criteria andEngineerTelNotBetween(String value1, String value2) {
            addCriterion("engineer_tel not between", value1, value2, "engineerTel");
            return (Criteria) this;
        }

        public Criteria andEngineerEmailIsNull() {
            addCriterion("engineer_email is null");
            return (Criteria) this;
        }

        public Criteria andEngineerEmailIsNotNull() {
            addCriterion("engineer_email is not null");
            return (Criteria) this;
        }

        public Criteria andEngineerEmailEqualTo(String value) {
            addCriterion("engineer_email =", value, "engineerEmail");
            return (Criteria) this;
        }

        public Criteria andEngineerEmailNotEqualTo(String value) {
            addCriterion("engineer_email <>", value, "engineerEmail");
            return (Criteria) this;
        }

        public Criteria andEngineerEmailGreaterThan(String value) {
            addCriterion("engineer_email >", value, "engineerEmail");
            return (Criteria) this;
        }

        public Criteria andEngineerEmailGreaterThanOrEqualTo(String value) {
            addCriterion("engineer_email >=", value, "engineerEmail");
            return (Criteria) this;
        }

        public Criteria andEngineerEmailLessThan(String value) {
            addCriterion("engineer_email <", value, "engineerEmail");
            return (Criteria) this;
        }

        public Criteria andEngineerEmailLessThanOrEqualTo(String value) {
            addCriterion("engineer_email <=", value, "engineerEmail");
            return (Criteria) this;
        }

        public Criteria andEngineerEmailLike(String value) {
            addCriterion("engineer_email like", value, "engineerEmail");
            return (Criteria) this;
        }

        public Criteria andEngineerEmailNotLike(String value) {
            addCriterion("engineer_email not like", value, "engineerEmail");
            return (Criteria) this;
        }

        public Criteria andEngineerEmailIn(List<String> values) {
            addCriterion("engineer_email in", values, "engineerEmail");
            return (Criteria) this;
        }

        public Criteria andEngineerEmailNotIn(List<String> values) {
            addCriterion("engineer_email not in", values, "engineerEmail");
            return (Criteria) this;
        }

        public Criteria andEngineerEmailBetween(String value1, String value2) {
            addCriterion("engineer_email between", value1, value2, "engineerEmail");
            return (Criteria) this;
        }

        public Criteria andEngineerEmailNotBetween(String value1, String value2) {
            addCriterion("engineer_email not between", value1, value2, "engineerEmail");
            return (Criteria) this;
        }

        public Criteria andEngineerMottoIsNull() {
            addCriterion("engineer_motto is null");
            return (Criteria) this;
        }

        public Criteria andEngineerMottoIsNotNull() {
            addCriterion("engineer_motto is not null");
            return (Criteria) this;
        }

        public Criteria andEngineerMottoEqualTo(String value) {
            addCriterion("engineer_motto =", value, "engineerMotto");
            return (Criteria) this;
        }

        public Criteria andEngineerMottoNotEqualTo(String value) {
            addCriterion("engineer_motto <>", value, "engineerMotto");
            return (Criteria) this;
        }

        public Criteria andEngineerMottoGreaterThan(String value) {
            addCriterion("engineer_motto >", value, "engineerMotto");
            return (Criteria) this;
        }

        public Criteria andEngineerMottoGreaterThanOrEqualTo(String value) {
            addCriterion("engineer_motto >=", value, "engineerMotto");
            return (Criteria) this;
        }

        public Criteria andEngineerMottoLessThan(String value) {
            addCriterion("engineer_motto <", value, "engineerMotto");
            return (Criteria) this;
        }

        public Criteria andEngineerMottoLessThanOrEqualTo(String value) {
            addCriterion("engineer_motto <=", value, "engineerMotto");
            return (Criteria) this;
        }

        public Criteria andEngineerMottoLike(String value) {
            addCriterion("engineer_motto like", value, "engineerMotto");
            return (Criteria) this;
        }

        public Criteria andEngineerMottoNotLike(String value) {
            addCriterion("engineer_motto not like", value, "engineerMotto");
            return (Criteria) this;
        }

        public Criteria andEngineerMottoIn(List<String> values) {
            addCriterion("engineer_motto in", values, "engineerMotto");
            return (Criteria) this;
        }

        public Criteria andEngineerMottoNotIn(List<String> values) {
            addCriterion("engineer_motto not in", values, "engineerMotto");
            return (Criteria) this;
        }

        public Criteria andEngineerMottoBetween(String value1, String value2) {
            addCriterion("engineer_motto between", value1, value2, "engineerMotto");
            return (Criteria) this;
        }

        public Criteria andEngineerMottoNotBetween(String value1, String value2) {
            addCriterion("engineer_motto not between", value1, value2, "engineerMotto");
            return (Criteria) this;
        }

        public Criteria andEngineerGitIsNull() {
            addCriterion("engineer_git is null");
            return (Criteria) this;
        }

        public Criteria andEngineerGitIsNotNull() {
            addCriterion("engineer_git is not null");
            return (Criteria) this;
        }

        public Criteria andEngineerGitEqualTo(String value) {
            addCriterion("engineer_git =", value, "engineerGit");
            return (Criteria) this;
        }

        public Criteria andEngineerGitNotEqualTo(String value) {
            addCriterion("engineer_git <>", value, "engineerGit");
            return (Criteria) this;
        }

        public Criteria andEngineerGitGreaterThan(String value) {
            addCriterion("engineer_git >", value, "engineerGit");
            return (Criteria) this;
        }

        public Criteria andEngineerGitGreaterThanOrEqualTo(String value) {
            addCriterion("engineer_git >=", value, "engineerGit");
            return (Criteria) this;
        }

        public Criteria andEngineerGitLessThan(String value) {
            addCriterion("engineer_git <", value, "engineerGit");
            return (Criteria) this;
        }

        public Criteria andEngineerGitLessThanOrEqualTo(String value) {
            addCriterion("engineer_git <=", value, "engineerGit");
            return (Criteria) this;
        }

        public Criteria andEngineerGitLike(String value) {
            addCriterion("engineer_git like", value, "engineerGit");
            return (Criteria) this;
        }

        public Criteria andEngineerGitNotLike(String value) {
            addCriterion("engineer_git not like", value, "engineerGit");
            return (Criteria) this;
        }

        public Criteria andEngineerGitIn(List<String> values) {
            addCriterion("engineer_git in", values, "engineerGit");
            return (Criteria) this;
        }

        public Criteria andEngineerGitNotIn(List<String> values) {
            addCriterion("engineer_git not in", values, "engineerGit");
            return (Criteria) this;
        }

        public Criteria andEngineerGitBetween(String value1, String value2) {
            addCriterion("engineer_git between", value1, value2, "engineerGit");
            return (Criteria) this;
        }

        public Criteria andEngineerGitNotBetween(String value1, String value2) {
            addCriterion("engineer_git not between", value1, value2, "engineerGit");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table engineer
     *
     * @mbg.generated do_not_delete_during_merge Mon Mar 30 20:44:51 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table engineer
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}