package com.sofency.ssm.pojo;

public class Fame {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fame.fame_id
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    private Integer fameId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fame.fame_level
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    private Integer fameLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fame.fame_name
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    private String fameName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fame.fame_description
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    private String fameDescription;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fame.fame_id
     *
     * @return the value of fame.fame_id
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    public Integer getFameId() {
        return fameId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fame.fame_id
     *
     * @param fameId the value for fame.fame_id
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    public void setFameId(Integer fameId) {
        this.fameId = fameId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fame.fame_level
     *
     * @return the value of fame.fame_level
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    public Integer getFameLevel() {
        return fameLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fame.fame_level
     *
     * @param fameLevel the value for fame.fame_level
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    public void setFameLevel(Integer fameLevel) {
        this.fameLevel = fameLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fame.fame_name
     *
     * @return the value of fame.fame_name
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    public String getFameName() {
        return fameName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fame.fame_name
     *
     * @param fameName the value for fame.fame_name
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    public void setFameName(String fameName) {
        this.fameName = fameName == null ? null : fameName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fame.fame_description
     *
     * @return the value of fame.fame_description
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    public String getFameDescription() {
        return fameDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fame.fame_description
     *
     * @param fameDescription the value for fame.fame_description
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    public void setFameDescription(String fameDescription) {
        this.fameDescription = fameDescription == null ? null : fameDescription.trim();
    }
}