package com.sofency.ssm.pojo;

import java.io.Serializable;
import java.util.Date;

public class GetFame extends GetFameKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column getfame.get_time
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    private Date getTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column getfame.get_time
     *
     * @return the value of getfame.get_time
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    public Date getGetTime() {
        return getTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column getfame.get_time
     *
     * @param getTime the value for getfame.get_time
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    public void setGetTime(Date getTime) {
        this.getTime = getTime;
    }
}