package com.sofency.ssm.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class GetFameExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table getfame
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table getfame
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table getfame
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table getfame
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    public GetFameExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table getfame
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table getfame
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table getfame
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table getfame
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table getfame
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table getfame
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table getfame
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table getfame
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table getfame
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table getfame
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table getfame
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andFameIdIsNull() {
            addCriterion("fame_id is null");
            return (Criteria) this;
        }

        public Criteria andFameIdIsNotNull() {
            addCriterion("fame_id is not null");
            return (Criteria) this;
        }

        public Criteria andFameIdEqualTo(Integer value) {
            addCriterion("fame_id =", value, "fameId");
            return (Criteria) this;
        }

        public Criteria andFameIdNotEqualTo(Integer value) {
            addCriterion("fame_id <>", value, "fameId");
            return (Criteria) this;
        }

        public Criteria andFameIdGreaterThan(Integer value) {
            addCriterion("fame_id >", value, "fameId");
            return (Criteria) this;
        }

        public Criteria andFameIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("fame_id >=", value, "fameId");
            return (Criteria) this;
        }

        public Criteria andFameIdLessThan(Integer value) {
            addCriterion("fame_id <", value, "fameId");
            return (Criteria) this;
        }

        public Criteria andFameIdLessThanOrEqualTo(Integer value) {
            addCriterion("fame_id <=", value, "fameId");
            return (Criteria) this;
        }

        public Criteria andFameIdIn(List<Integer> values) {
            addCriterion("fame_id in", values, "fameId");
            return (Criteria) this;
        }

        public Criteria andFameIdNotIn(List<Integer> values) {
            addCriterion("fame_id not in", values, "fameId");
            return (Criteria) this;
        }

        public Criteria andFameIdBetween(Integer value1, Integer value2) {
            addCriterion("fame_id between", value1, value2, "fameId");
            return (Criteria) this;
        }

        public Criteria andFameIdNotBetween(Integer value1, Integer value2) {
            addCriterion("fame_id not between", value1, value2, "fameId");
            return (Criteria) this;
        }

        public Criteria andEngineerIdIsNull() {
            addCriterion("engineer_id is null");
            return (Criteria) this;
        }

        public Criteria andEngineerIdIsNotNull() {
            addCriterion("engineer_id is not null");
            return (Criteria) this;
        }

        public Criteria andEngineerIdEqualTo(Integer value) {
            addCriterion("engineer_id =", value, "engineerId");
            return (Criteria) this;
        }

        public Criteria andEngineerIdNotEqualTo(Integer value) {
            addCriterion("engineer_id <>", value, "engineerId");
            return (Criteria) this;
        }

        public Criteria andEngineerIdGreaterThan(Integer value) {
            addCriterion("engineer_id >", value, "engineerId");
            return (Criteria) this;
        }

        public Criteria andEngineerIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("engineer_id >=", value, "engineerId");
            return (Criteria) this;
        }

        public Criteria andEngineerIdLessThan(Integer value) {
            addCriterion("engineer_id <", value, "engineerId");
            return (Criteria) this;
        }

        public Criteria andEngineerIdLessThanOrEqualTo(Integer value) {
            addCriterion("engineer_id <=", value, "engineerId");
            return (Criteria) this;
        }

        public Criteria andEngineerIdIn(List<Integer> values) {
            addCriterion("engineer_id in", values, "engineerId");
            return (Criteria) this;
        }

        public Criteria andEngineerIdNotIn(List<Integer> values) {
            addCriterion("engineer_id not in", values, "engineerId");
            return (Criteria) this;
        }

        public Criteria andEngineerIdBetween(Integer value1, Integer value2) {
            addCriterion("engineer_id between", value1, value2, "engineerId");
            return (Criteria) this;
        }

        public Criteria andEngineerIdNotBetween(Integer value1, Integer value2) {
            addCriterion("engineer_id not between", value1, value2, "engineerId");
            return (Criteria) this;
        }

        public Criteria andGetTimeIsNull() {
            addCriterion("get_time is null");
            return (Criteria) this;
        }

        public Criteria andGetTimeIsNotNull() {
            addCriterion("get_time is not null");
            return (Criteria) this;
        }

        public Criteria andGetTimeEqualTo(Date value) {
            addCriterion("get_time =", value, "getTime");
            return (Criteria) this;
        }

        public Criteria andGetTimeNotEqualTo(Date value) {
            addCriterion("get_time <>", value, "getTime");
            return (Criteria) this;
        }

        public Criteria andGetTimeGreaterThan(Date value) {
            addCriterion("get_time >", value, "getTime");
            return (Criteria) this;
        }

        public Criteria andGetTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("get_time >=", value, "getTime");
            return (Criteria) this;
        }

        public Criteria andGetTimeLessThan(Date value) {
            addCriterion("get_time <", value, "getTime");
            return (Criteria) this;
        }

        public Criteria andGetTimeLessThanOrEqualTo(Date value) {
            addCriterion("get_time <=", value, "getTime");
            return (Criteria) this;
        }

        public Criteria andGetTimeIn(List<Date> values) {
            addCriterion("get_time in", values, "getTime");
            return (Criteria) this;
        }

        public Criteria andGetTimeNotIn(List<Date> values) {
            addCriterion("get_time not in", values, "getTime");
            return (Criteria) this;
        }

        public Criteria andGetTimeBetween(Date value1, Date value2) {
            addCriterion("get_time between", value1, value2, "getTime");
            return (Criteria) this;
        }

        public Criteria andGetTimeNotBetween(Date value1, Date value2) {
            addCriterion("get_time not between", value1, value2, "getTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table getfame
     *
     * @mbg.generated do_not_delete_during_merge Mon Mar 30 20:44:51 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table getfame
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}