package com.sofency.ssm.pojo;

import java.io.Serializable;

public class GetFameKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column getfame.fame_id
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    private Integer fameId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column getfame.engineer_id
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    private Integer engineerId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column getfame.fame_id
     *
     * @return the value of getfame.fame_id
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    public Integer getFameId() {
        return fameId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column getfame.fame_id
     *
     * @param fameId the value for getfame.fame_id
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    public void setFameId(Integer fameId) {
        this.fameId = fameId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column getfame.engineer_id
     *
     * @return the value of getfame.engineer_id
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    public Integer getEngineerId() {
        return engineerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column getfame.engineer_id
     *
     * @param engineerId the value for getfame.engineer_id
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    public void setEngineerId(Integer engineerId) {
        this.engineerId = engineerId;
    }
}