package com.sofency.ssm.pojo;

import org.springframework.stereotype.Service;

import java.io.Serializable;

public class Institute implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column institute.inst_id
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    private Integer instId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column institute.inst_name
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    private String instName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column institute.inst_id
     *
     * @return the value of institute.inst_id
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    public Integer getInstId() {
        return instId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column institute.inst_id
     *
     * @param instId the value for institute.inst_id
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    public void setInstId(Integer instId) {
        this.instId = instId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column institute.inst_name
     *
     * @return the value of institute.inst_name
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    public String getInstName() {
        return instName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column institute.inst_name
     *
     * @param instName the value for institute.inst_name
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    public void setInstName(String instName) {
        this.instName = instName == null ? null : instName.trim();
    }
}