package com.sofency.ssm.pojo;

public class MajorKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major.major_id
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    private Integer majorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major.inst_id
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    private Integer instId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major.major_id
     *
     * @return the value of major.major_id
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    public Integer getMajorId() {
        return majorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major.major_id
     *
     * @param majorId the value for major.major_id
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    public void setMajorId(Integer majorId) {
        this.majorId = majorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major.inst_id
     *
     * @return the value of major.inst_id
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    public Integer getInstId() {
        return instId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major.inst_id
     *
     * @param instId the value for major.inst_id
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    public void setInstId(Integer instId) {
        this.instId = instId;
    }
}