package com.sofency.ssm.pojo;

public class Manager {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.manager_id
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    private Integer managerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.username
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.userpwd
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    private String userpwd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.manager_id
     *
     * @return the value of manager.manager_id
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    public Integer getManagerId() {
        return managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.manager_id
     *
     * @param managerId the value for manager.manager_id
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    public void setManagerId(Integer managerId) {
        this.managerId = managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.username
     *
     * @return the value of manager.username
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.username
     *
     * @param username the value for manager.username
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.userpwd
     *
     * @return the value of manager.userpwd
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    public String getUserpwd() {
        return userpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.userpwd
     *
     * @param userpwd the value for manager.userpwd
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    public void setUserpwd(String userpwd) {
        this.userpwd = userpwd == null ? null : userpwd.trim();
    }
}