package com.sofency.ssm.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class MessageExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table message
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table message
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table message
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    public MessageExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table message
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMsgIdIsNull() {
            addCriterion("msg_id is null");
            return (Criteria) this;
        }

        public Criteria andMsgIdIsNotNull() {
            addCriterion("msg_id is not null");
            return (Criteria) this;
        }

        public Criteria andMsgIdEqualTo(Integer value) {
            addCriterion("msg_id =", value, "msgId");
            return (Criteria) this;
        }

        public Criteria andMsgIdNotEqualTo(Integer value) {
            addCriterion("msg_id <>", value, "msgId");
            return (Criteria) this;
        }

        public Criteria andMsgIdGreaterThan(Integer value) {
            addCriterion("msg_id >", value, "msgId");
            return (Criteria) this;
        }

        public Criteria andMsgIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("msg_id >=", value, "msgId");
            return (Criteria) this;
        }

        public Criteria andMsgIdLessThan(Integer value) {
            addCriterion("msg_id <", value, "msgId");
            return (Criteria) this;
        }

        public Criteria andMsgIdLessThanOrEqualTo(Integer value) {
            addCriterion("msg_id <=", value, "msgId");
            return (Criteria) this;
        }

        public Criteria andMsgIdIn(List<Integer> values) {
            addCriterion("msg_id in", values, "msgId");
            return (Criteria) this;
        }

        public Criteria andMsgIdNotIn(List<Integer> values) {
            addCriterion("msg_id not in", values, "msgId");
            return (Criteria) this;
        }

        public Criteria andMsgIdBetween(Integer value1, Integer value2) {
            addCriterion("msg_id between", value1, value2, "msgId");
            return (Criteria) this;
        }

        public Criteria andMsgIdNotBetween(Integer value1, Integer value2) {
            addCriterion("msg_id not between", value1, value2, "msgId");
            return (Criteria) this;
        }

        public Criteria andMsgHeaderIsNull() {
            addCriterion("msg_header is null");
            return (Criteria) this;
        }

        public Criteria andMsgHeaderIsNotNull() {
            addCriterion("msg_header is not null");
            return (Criteria) this;
        }

        public Criteria andMsgHeaderEqualTo(String value) {
            addCriterion("msg_header =", value, "msgHeader");
            return (Criteria) this;
        }

        public Criteria andMsgHeaderNotEqualTo(String value) {
            addCriterion("msg_header <>", value, "msgHeader");
            return (Criteria) this;
        }

        public Criteria andMsgHeaderGreaterThan(String value) {
            addCriterion("msg_header >", value, "msgHeader");
            return (Criteria) this;
        }

        public Criteria andMsgHeaderGreaterThanOrEqualTo(String value) {
            addCriterion("msg_header >=", value, "msgHeader");
            return (Criteria) this;
        }

        public Criteria andMsgHeaderLessThan(String value) {
            addCriterion("msg_header <", value, "msgHeader");
            return (Criteria) this;
        }

        public Criteria andMsgHeaderLessThanOrEqualTo(String value) {
            addCriterion("msg_header <=", value, "msgHeader");
            return (Criteria) this;
        }

        public Criteria andMsgHeaderLike(String value) {
            addCriterion("msg_header like", value, "msgHeader");
            return (Criteria) this;
        }

        public Criteria andMsgHeaderNotLike(String value) {
            addCriterion("msg_header not like", value, "msgHeader");
            return (Criteria) this;
        }

        public Criteria andMsgHeaderIn(List<String> values) {
            addCriterion("msg_header in", values, "msgHeader");
            return (Criteria) this;
        }

        public Criteria andMsgHeaderNotIn(List<String> values) {
            addCriterion("msg_header not in", values, "msgHeader");
            return (Criteria) this;
        }

        public Criteria andMsgHeaderBetween(String value1, String value2) {
            addCriterion("msg_header between", value1, value2, "msgHeader");
            return (Criteria) this;
        }

        public Criteria andMsgHeaderNotBetween(String value1, String value2) {
            addCriterion("msg_header not between", value1, value2, "msgHeader");
            return (Criteria) this;
        }

        public Criteria andMsgTimeIsNull() {
            addCriterion("msg_time is null");
            return (Criteria) this;
        }

        public Criteria andMsgTimeIsNotNull() {
            addCriterion("msg_time is not null");
            return (Criteria) this;
        }

        public Criteria andMsgTimeEqualTo(Date value) {
            addCriterion("msg_time =", value, "msgTime");
            return (Criteria) this;
        }

        public Criteria andMsgTimeNotEqualTo(Date value) {
            addCriterion("msg_time <>", value, "msgTime");
            return (Criteria) this;
        }

        public Criteria andMsgTimeGreaterThan(Date value) {
            addCriterion("msg_time >", value, "msgTime");
            return (Criteria) this;
        }

        public Criteria andMsgTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("msg_time >=", value, "msgTime");
            return (Criteria) this;
        }

        public Criteria andMsgTimeLessThan(Date value) {
            addCriterion("msg_time <", value, "msgTime");
            return (Criteria) this;
        }

        public Criteria andMsgTimeLessThanOrEqualTo(Date value) {
            addCriterion("msg_time <=", value, "msgTime");
            return (Criteria) this;
        }

        public Criteria andMsgTimeIn(List<Date> values) {
            addCriterion("msg_time in", values, "msgTime");
            return (Criteria) this;
        }

        public Criteria andMsgTimeNotIn(List<Date> values) {
            addCriterion("msg_time not in", values, "msgTime");
            return (Criteria) this;
        }

        public Criteria andMsgTimeBetween(Date value1, Date value2) {
            addCriterion("msg_time between", value1, value2, "msgTime");
            return (Criteria) this;
        }

        public Criteria andMsgTimeNotBetween(Date value1, Date value2) {
            addCriterion("msg_time not between", value1, value2, "msgTime");
            return (Criteria) this;
        }

        public Criteria andMsgVisitedIsNull() {
            addCriterion("msg_visited is null");
            return (Criteria) this;
        }

        public Criteria andMsgVisitedIsNotNull() {
            addCriterion("msg_visited is not null");
            return (Criteria) this;
        }

        public Criteria andMsgVisitedEqualTo(Integer value) {
            addCriterion("msg_visited =", value, "msgVisited");
            return (Criteria) this;
        }

        public Criteria andMsgVisitedNotEqualTo(Integer value) {
            addCriterion("msg_visited <>", value, "msgVisited");
            return (Criteria) this;
        }

        public Criteria andMsgVisitedGreaterThan(Integer value) {
            addCriterion("msg_visited >", value, "msgVisited");
            return (Criteria) this;
        }

        public Criteria andMsgVisitedGreaterThanOrEqualTo(Integer value) {
            addCriterion("msg_visited >=", value, "msgVisited");
            return (Criteria) this;
        }

        public Criteria andMsgVisitedLessThan(Integer value) {
            addCriterion("msg_visited <", value, "msgVisited");
            return (Criteria) this;
        }

        public Criteria andMsgVisitedLessThanOrEqualTo(Integer value) {
            addCriterion("msg_visited <=", value, "msgVisited");
            return (Criteria) this;
        }

        public Criteria andMsgVisitedIn(List<Integer> values) {
            addCriterion("msg_visited in", values, "msgVisited");
            return (Criteria) this;
        }

        public Criteria andMsgVisitedNotIn(List<Integer> values) {
            addCriterion("msg_visited not in", values, "msgVisited");
            return (Criteria) this;
        }

        public Criteria andMsgVisitedBetween(Integer value1, Integer value2) {
            addCriterion("msg_visited between", value1, value2, "msgVisited");
            return (Criteria) this;
        }

        public Criteria andMsgVisitedNotBetween(Integer value1, Integer value2) {
            addCriterion("msg_visited not between", value1, value2, "msgVisited");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table message
     *
     * @mbg.generated do_not_delete_during_merge Mon Mar 30 20:44:51 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table message
     *
     * @mbg.generated Mon Mar 30 20:44:51 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}